services:
  financeyu-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: financeyu-front
    ports:
      - "4173:4173"
    restart: unless-stopped
